dist: trusty
sudo: required
language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - zlib1g-dev
      - libdbus-glib-1-dev

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.zip &&
  unzip master.zip &&
  mv kcov-master kcov &&
  mkdir kcov/build &&
  cd kcov/build &&
  cmake .. &&
  make &&
  for file in target/debug/IMAPServer-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; src/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0ME1UUk5vcmQlM0FtYXRyaXguZmZzbGZsLm5ldC8lMjFzRk51Q2RCZU5MU05HQlFmeWYlM0FtYXRyaXguZmZzbGZsLm5ldA"
        on_success: always  # always|never|change
        on_failure: always
        on_start: always
