[package]
name = "IMAPServer"
version = "0.0.0"
authors = ["MTRNord <mtrnord1@gmail.com>"]
description = "A Basic IMAP Server written in Rust (WIP)"
repository = "https://github.com/Nordgedanken/IMAPServer-rs"
keywords = ["imap","tcp", "server", "bin", "email"]
categories = ["email", "network-programming"]
license = "GPL-3.0"
exclude = [
    ".idea/*",
    ".gitignore"
]

[dependencies]
app_dirs = "1.1.1"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
bytes = "0.4"
mailparse = "0.5"
mysql = "11.1"
log = "0.3"
simplelog = "0.4"
pwhash = "0.1"

[dependencies.config]
version = "0.4.1"
features = ["yaml"]

[package.metadata.deb]
maintainer = "Marcel Radzio <info@nordgedanken.de>"
copyright = "2017, Marcel Radzio <info@nordgedanken.de>"
license_file = ["LICENSE", "4"]
extended_description = """\
A IMAP Server written in Rust."""
depends = "mysql"
section = "mail"
priority = "optional"
assets = [
    ["target/release/IMAPServer", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/IMAPServer/README", "644"],
]
